### ISSUE TITLE
Binding checked flag with a state does not update the checkbox

### ISSUE THREAD

**Issue by binarykitchen** [radubrehar/react-checkbox#2]
```coffee
  _renderSelect: (cellData, cellDataKey, rowData, index) ->
    <Checkbox
      checked={@state.selected[index]}
    />
```

When I change the state of the selected array somewhere else in the code, the checkbox does not get updated. Looks like it's a bug.

**Comment by radubrehar** [comment]
I have tested it again and have no problem. What version are you using? I'm testing 0.1.3, which works ok for me. Please try to create a reduced test-page and see if you can reproduce it. Let me know what you find please. 
Thanks

**Comment by binarykitchen** [comment]
I believe the problem has nothing to do with your component, so I have moved this issue here https://github.com/facebook/react/issues/3204
